  filmfusion-api:
    build:
      context: .
      dockerfile: Dockerfile.api   # See example in previous message
    container_name: filmfusion_api
    environment:
      - DATABASE_URL=postgresql://filmfusion_user:filmfusion_pass@postgres:5432/filmfusion
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models

  filmfusion-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard  # See example in previous message
    container_name: filmfusion_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
