services:
  postgres:
    image: postgres:13
    container_name: filmfusion_postgres
    environment:
      POSTGRES_DB: filmfusion
      POSTGRES_USER: filmfusion_user
      POSTGRES_PASSWORD: filmfusion_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/schemas:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U filmfusion_user -d filmfusion"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:6-alpine
    container_name: filmfusion_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  airflow-init:
    image: apache/airflow:2.6.3
    container_name: filmfusion_airflow_init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://filmfusion_user:filmfusion_pass@postgres:5432/filmfusion
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      _AIRFLOW_DB_MIGRATE: 'True'
      _AIRFLOW_WWW_USER_CREATE: 'True'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "airflow db upgrade && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@filmfusion.com --password admin"

  airflow-webserver:
    image: apache/airflow:2.6.3
    container_name: filmfusion_airflow_webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://filmfusion_user:filmfusion_pass@postgres:5432/filmfusion
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    depends_on:
      - airflow-init
      - postgres
      - redis
    command: airflow webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  airflow-scheduler:
    image: apache/airflow:2.6.3
    container_name: filmfusion_airflow_scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://filmfusion_user:filmfusion_pass@postgres:5432/filmfusion
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    depends_on:
      - airflow-init
      - postgres
      - redis
    command: airflow scheduler

  

  filmfusion-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: filmfusion_api
    environment:
      - DATABASE_URL=postgresql://filmfusion_user:filmfusion_pass@postgres:5432/filmfusion
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models

  filmfusion-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: filmfusion_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - filmfusion-api
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models

volumes:
  postgres_data:
